### ISSUE TITLE
Implementación Tarea 2

### ISSUE THREAD

**Issue by jtcaraball** [IIC2440/Syllabus-2023-1#16]
Hola! En la tarea 2 se habla harto de preparar mensajes y enviarlos entre nodos usando RDDs. La intención con esto es que guardemos el grafo (de alguna forma) en RDDS y utilicemos las primitivas de `map`, `reduce` , `filter`, etc. para computar los algoritmos o hay alguna forma de en efecto dividir cada nodo el grafo en un 'nodo de computo' de Spark distinto y jugar con el paso de mensajes de Spark under the hood?

Muchas gracias!

**Comment by alanezz** [comment]
Hola, la idea es que usen los RDDs como vimos en clases + las primitivas para computar los algoritmos. La forma de hacerlo es simular ese paso de mensajes, pero esto lo tienen que hacer con map, reduce, joins y las otras funciones.
