### ISSUE TITLE
Control MidTerm: temario, metodología de evaluación y duración.

### ISSUE THREAD

**Issue by larryuc** [IIC2440/Syllabus-2023-1#6]
Estimados, en el home del github se indica que esta semana será la evaluación Midterm en horario de clases <html>
<body>

24/04 | Midterm (En horario de clases)
-- | --

</body>
</html>

Las consultas son: 

- ¿qué contenidos serán evaluados?
- ¿Es de desarrollo con computador o con palabras escrita?
- ¿Cual será la hora en donde la tomarán, al inicio del modulo o al segundo..?
- y por ultimo.. ¿su duración? 

desde ya muchas gracias.

**Comment by juanreutter** [comment]
Como les mencioné el miércoles pasado:
 
Entra toda la materia, el énfasis es en preguntas conceptuales. Pueden llevar todo tipo de material, pero análogo. 
Se toma en clases, en la sala de clases, el midterm es todo lo que haremos y comienza cerca de las 3:30.

Voy a mandar un correo sobre esto, pero les recuerdo que las clases de este curso son obligatorias (pueden verlo en el programa).
