### ISSUE TITLE
Enfoque datos Tarea 1

### ISSUE THREAD

**Issue by Juanvg213** [IIC2440/Syllabus-2023-1#7]
Hola profe!
Tengo una duda respecto a cómo se espera que carguemos los datos para la tarea. Intentamos cargarlos en Google Colab como un dataframe de Pandas y Colab no nos lo permitió, como era de esperar. Luego intentamos hacer lo mismo en el computador de manera local (con 16GB de RAM) y por algún motivo el pc igual se le lageaba al intentar hacer esto. Otro approach que tenemos es ir cargando los datos en memoria línea por línea, pero estuvimos corriendolo por unos 15 minutos y aun así no cargaba.
Mi pregunta es cuál método recomienda usted para cargar los datos, y cuánto es razonable esperar a que se carguen sin que tengamos que pensar que estamos haciendo algo mal para partir de nuevo con otro approach.
Gracias!

**Comment by juanreutter** [comment]
Conteste esto por correo, pero lo contesto aca también: Los datos no deberían presentar problemas para ser cargados con pandas, en ningún computador con al menos 4GB de RAM. De cualquier forma, lo más razonable es cargarlo de a pedacitos, en mitades, o en cuartos, o algo así. Línea por linea tampoco es eficiente, por que el buffer de los discos pueden almacenar mucho más que una línea!

**Comment by Juanvg213** [comment]
Efectivamente si funciona cargar los datos, creo que colab me había asignado justo un pc con malos recursos, gracias en todo caso profe!
